### ISSUE TITLE
Custom Provider volcengine-plan Fails with TypeError: Unexpected Keyword Argument 'provider_id'

### ISSUE THREAD

**Issue by hjs2015** [agentscope-ai/CoPaw#2919]
## 🐛 Bug Description

When using the custom provider `volcengine-plan` (Volcano Engine Coding Plan / Doubao models) to make LLM calls, the system throws a TypeError that completely blocks usage:

```
TypeError: AsyncCompletions.create() got an unexpected keyword argument 'provider_id'
```

## 🔍 Root Cause

The custom provider configuration template incorrectly includes `provider_id` in the `generate_kwargs` section, which is then passed directly to the OpenAI SDK's `chat.completions.create()` method. However, `provider_id` is not a valid OpenAI SDK parameter.

**Problematic Configuration** (`/root/.copaw.secret/providers/custom/volcengine-plan.json`):

```json
{
  "id": "volcengine-plan",
  "base_url": "https://ark.cn-beijing.volces.com/api/coding/v3",
  "api_key": "...",
  "chat_model": "OpenAIChatModel",
  "generate_kwargs": {
    "provider_id": "volcengine-plan",  // ❌ BUG: Invalid parameter
    "model": "glm-4.7",
    "scope": "chat"
  }
}
```

## 📝 Steps to Reproduce

1. Create custom provider config at `/root/.copaw.secret/providers/custom/volcengine-plan.json`
2. Include `provider_id` in `generate_kwargs` (as shown above)
3. Set provider as active in agent.json
4. Attempt to make any LLM call
5. **Result**: TypeError exception

## ✅ Expected Behavior

- Custom providers should work without manual configuration edits
- `provider_id` should be handled internally by CoPaw (top-level `"id"` field)
- Only valid OpenAI SDK parameters should be in `generate_kwargs`

## 🔧 Proposed Fix

Remove `provider_id` from `generate_kwargs`:

```json
// Before (❌ Buggy)
"generate_kwargs": {
  "provider_id": "volcengine-plan",
  "model": "glm-4.7",
  "scope": "chat"
}

// After (✅ Fixed)
"generate_kwargs": {
  "model": "glm-4.7",
  "scope": "chat"
}
```

## 🧪 Verification

**API Test** (works independently):
```bash
curl -X POST "https://ark.cn-beijing.volces.com/api/coding/v3/chat/completions" \
  -H "Authorization: Bearer YOUR_API_KEY" \
  -d '{"model":"Doubao-Seed-2.0-Code","messages":[{"role":"user","content":"test"}]}'
# ✅ Returns successful response
```

**CoPaw Integration** (fails):
```python
# Any LLM call through volcengine-plan provider
# ❌ TypeError: AsyncCompletions.create() got an unexpected keyword argument 'provider_id'
```

## 📊 Impact

| Aspect | Details |
|--------|---------|
| **Severity** | 🔴 High - Complete block of provider usage |
| **Affected Users** | All users using volcengine-plan provider |
| **Workaround** | Manual config edit (remove provider_id from generate_kwargs) |
| **Data Loss** | None |
| **Security** | None |

## 💡 Recommendations

1. **Fix configuration template** for volcengine-plan provider
2. **Add validation** to prevent invalid parameters in generate_kwargs
3. **Audit other custom providers** for the same issue
4. **Document** correct configuration format
5. **Add schema validation** for provider configurations

## 📎 System Information

- **OS**: Linux 6.8.0-106-generic (Ubuntu)
- **Python**: 3.12.3
- **CoPaw Version**: 1.0.0.post3
- **Provider**: volcengine-plan (Volcano Engine / Doubao)
- **Models**: Doubao-Seed-2.0-Code, glm-4.7, kimi-k2.5
- **Date**: 2026-04-03

## 🏷️ Labels

- `bug`
- `configuration`
- `provider-integration`
- `volcengine`
- `high-severity`

---

**Please fix this configuration bug to enable volcengine-plan provider usage.** 🙏

**Comment by hjs2015** [comment]
## 🔄 Update: Same issue with `scope` parameter (2026-04-04)

The same error has occurred again with a different invalid parameter:

```
TypeError: AsyncCompletions.create() got an unexpected keyword argument 'scope'
```

### Current Error
- **Error Type**: `TypeError: AsyncCompletions.create() got an unexpected keyword argument 'scope'`
- **Location**: Same configuration file `/root/.copaw.secret/providers/custom/volcengine-plan.json`
- **Previous Fix**: Removed `provider_id` from `generate_kwargs` (commit successful)
- **New Issue**: `scope` parameter is also invalid and needs to be removed

### Request
Could you please check if there are any other invalid parameters in the `generate_kwargs` configuration for the volcengine-plan provider? It seems the configuration schema may have multiple deprecated/invalid fields.

### System Info
| Item | Value |
|------|-------|
| **CoPaw Version** | `1.0.0.post3` |
| **Installation** | pip (`copaw==1.0.0.post3`) |
| **Provider** | volcengine-plan (Volcengine Ark) |
| **Model** | Doubao-Seed-2.0-Code |
| **Base URL** | `https://ark.cn-beijing.volces.com/api/coding/v3` |
| **OS** | Linux 6.8.0-106-generic (x86_64) |
| **Python** | 3.12 |

Thank you!

**Comment by pan-x-c** [comment]
1. provider 的 `generate_kwargs` 配置中并不存在 `provider_id` 这个配置项，请按照[文档](https://copaw.agentscope.io/docs/models#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BE%9B%E5%BA%94%E5%95%86%E9%85%8D%E7%BD%AE)中的步骤进行配置，在不理解 CoPaw 配置逻辑的情况下请不要直接修改 provider 配置文件
2. `scope` 域是 0.2.0 版本中加入的新增功能，出现该报错说明前端代码还没有更新，一般该问题只会出现在源码安装的场景，建议参考[文档](https://github.com/agentscope-ai/CoPaw?tab=readme-ov-file#install-from-source)中的内容重新安装
